# Generated by Django 4.1.2 on 2023-07-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.CharField(default='asas', max_length=50),
        ),
    ]
