# Generated by Django 4.2.3 on 2023-08-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='email',
        ),
    ]
